"""add data_folders data_sets and run data columns

Revision ID: b6607df2f192
Revises: f4ff3a41298b
Create Date: 2026-03-24 00:20:02.624973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'b6607df2f192'
down_revision: Union[str, Sequence[str], None] = 'f4ff3a41298b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_data_folder_name')
    )
    op.create_index(op.f('ix_data_folders_project_id'), 'data_folders', ['project_id'], unique=False)
    op.create_table('data_sets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('environment', sa.String(length=100), nullable=False),
    sa.Column('variables', sa.JSON(), nullable=False),
    sa.Column('rows', sa.JSON(), nullable=False),
    sa.Column('is_default', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['folder_id'], ['data_folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'folder_id', 'name', name='uq_data_set_name')
    )
    op.create_index(op.f('ix_data_sets_folder_id'), 'data_sets', ['folder_id'], unique=False)
    op.create_index(op.f('ix_data_sets_project_id'), 'data_sets', ['project_id'], unique=False)
    op.add_column('runs', sa.Column('data_set_id', sa.Integer(), nullable=True))
    op.add_column('runs', sa.Column('data_row_index', sa.Integer(), nullable=True))
    op.alter_column('runs', 'failure_category',
               existing_type=sa.VARCHAR(length=50),
               nullable=False,
               existing_server_default=sa.text("('')"))
    op.alter_column('runs', 'summary',
               existing_type=sqlite.JSON(),
               nullable=True)
    op.alter_column('runs', 'artifacts',
               existing_type=sqlite.JSON(),
               nullable=True)
    op.create_index(op.f('ix_runs_batch_run_id'), 'runs', ['batch_run_id'], unique=False)
    op.create_index(op.f('ix_runs_build_id'), 'runs', ['build_id'], unique=False)
    op.create_index(op.f('ix_runs_data_set_id'), 'runs', ['data_set_id'], unique=False)
    op.create_index(op.f('ix_runs_test_id'), 'runs', ['test_id'], unique=False)
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.create_foreign_key(None, 'runs', 'batch_runs', ['batch_run_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'runs', 'data_sets', ['data_set_id'], ['id'], ondelete='SET NULL')
    op.create_index(op.f('ix_screen_library_build_id'), 'screen_library', ['build_id'], unique=False)
    op.create_index(op.f('ix_screen_library_folder_id'), 'screen_library', ['folder_id'], unique=False)
    op.drop_constraint(None, 'screen_library', type_='foreignkey')
    op.create_foreign_key(None, 'screen_library', 'screen_folders', ['folder_id'], ['id'], ondelete='SET NULL')
    op.alter_column('tests', 'platform_steps',
               existing_type=sqlite.JSON(),
               nullable=False,
               existing_server_default=sa.text("'{}'"))
    op.alter_column('tests', 'fix_history',
               existing_type=sqlite.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'"))
    op.create_index(op.f('ix_tests_prerequisite_test_id'), 'tests', ['prerequisite_test_id'], unique=False)
    op.create_index(op.f('ix_tests_suite_id'), 'tests', ['suite_id'], unique=False)
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.create_foreign_key(None, 'tests', 'tests', ['prerequisite_test_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'tests', 'test_suites', ['suite_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.create_foreign_key(None, 'tests', 'test_suites', ['suite_id'], ['id'])
    op.create_foreign_key(None, 'tests', 'tests', ['prerequisite_test_id'], ['id'])
    op.drop_index(op.f('ix_tests_suite_id'), table_name='tests')
    op.drop_index(op.f('ix_tests_prerequisite_test_id'), table_name='tests')
    op.alter_column('tests', 'fix_history',
               existing_type=sqlite.JSON(),
               nullable=True,
               existing_server_default=sa.text("'[]'"))
    op.alter_column('tests', 'platform_steps',
               existing_type=sqlite.JSON(),
               nullable=True,
               existing_server_default=sa.text("'{}'"))
    op.drop_constraint(None, 'screen_library', type_='foreignkey')
    op.create_foreign_key(None, 'screen_library', 'screen_folders', ['folder_id'], ['id'])
    op.drop_index(op.f('ix_screen_library_folder_id'), table_name='screen_library')
    op.drop_index(op.f('ix_screen_library_build_id'), table_name='screen_library')
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.drop_constraint(None, 'runs', type_='foreignkey')
    op.create_foreign_key(None, 'runs', 'batch_runs', ['batch_run_id'], ['id'])
    op.drop_index(op.f('ix_runs_test_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_data_set_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_build_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_batch_run_id'), table_name='runs')
    op.alter_column('runs', 'artifacts',
               existing_type=sqlite.JSON(),
               nullable=False)
    op.alter_column('runs', 'summary',
               existing_type=sqlite.JSON(),
               nullable=False)
    op.alter_column('runs', 'failure_category',
               existing_type=sa.VARCHAR(length=50),
               nullable=True,
               existing_server_default=sa.text("('')"))
    op.drop_column('runs', 'data_row_index')
    op.drop_column('runs', 'data_set_id')
    op.drop_index(op.f('ix_data_sets_project_id'), table_name='data_sets')
    op.drop_index(op.f('ix_data_sets_folder_id'), table_name='data_sets')
    op.drop_table('data_sets')
    op.drop_index(op.f('ix_data_folders_project_id'), table_name='data_folders')
    op.drop_table('data_folders')
    # ### end Alembic commands ###
