"""initial schema

Revision ID: f4ff3a41298b
Revises: 
Create Date: 2026-03-23 22:22:08.052853

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4ff3a41298b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_name'), 'projects', ['name'], unique=True)
    op.create_table('batch_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(length=30), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Integer(), nullable=False),
    sa.Column('failed', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_runs_project_id'), 'batch_runs', ['project_id'], unique=False)
    op.create_table('builds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('build_metadata', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_builds_project_id'), 'builds', ['project_id'], unique=False)
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_modules_project_id'), 'modules', ['project_id'], unique=False)
    op.create_table('screen_folders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'name', name='uq_screen_folder_name')
    )
    op.create_index(op.f('ix_screen_folders_project_id'), 'screen_folders', ['project_id'], unique=False)
    op.create_table('screen_library',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=True),
    sa.Column('folder_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('xml_snapshot', sa.Text(), nullable=False),
    sa.Column('screenshot_path', sa.String(length=500), nullable=True),
    sa.Column('captured_at', sa.DateTime(), nullable=False),
    sa.Column('captured_by', sa.String(length=200), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('auto_captured', sa.Integer(), nullable=False),
    sa.Column('screen_type', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['folder_id'], ['screen_folders.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'build_id', 'name', 'platform', name='uq_screen_per_build')
    )
    op.create_index(op.f('ix_screen_library_build_id'), 'screen_library', ['build_id'], unique=False)
    op.create_index(op.f('ix_screen_library_folder_id'), 'screen_library', ['folder_id'], unique=False)
    op.create_index(op.f('ix_screen_library_project_id'), 'screen_library', ['project_id'], unique=False)
    op.create_table('test_suites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_test_suites_module_id'), 'test_suites', ['module_id'], unique=False)
    op.create_table('tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('suite_id', sa.Integer(), nullable=True),
    sa.Column('prerequisite_test_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('platform_steps', sa.JSON(), nullable=False),
    sa.Column('acceptance_criteria', sa.Text(), nullable=True),
    sa.Column('fix_history', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['prerequisite_test_id'], ['tests.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['suite_id'], ['test_suites.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tests_prerequisite_test_id'), 'tests', ['prerequisite_test_id'], unique=False)
    op.create_index(op.f('ix_tests_project_id'), 'tests', ['project_id'], unique=False)
    op.create_index(op.f('ix_tests_suite_id'), 'tests', ['suite_id'], unique=False)
    op.create_table('runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('build_id', sa.Integer(), nullable=True),
    sa.Column('test_id', sa.Integer(), nullable=True),
    sa.Column('batch_run_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('device_target', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('finished_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('failure_category', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.JSON(), nullable=True),
    sa.Column('artifacts', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['batch_run_id'], ['batch_runs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['build_id'], ['builds.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_runs_batch_run_id'), 'runs', ['batch_run_id'], unique=False)
    op.create_index(op.f('ix_runs_build_id'), 'runs', ['build_id'], unique=False)
    op.create_index(op.f('ix_runs_project_id'), 'runs', ['project_id'], unique=False)
    op.create_index(op.f('ix_runs_test_id'), 'runs', ['test_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_runs_test_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_project_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_build_id'), table_name='runs')
    op.drop_index(op.f('ix_runs_batch_run_id'), table_name='runs')
    op.drop_table('runs')
    op.drop_index(op.f('ix_tests_suite_id'), table_name='tests')
    op.drop_index(op.f('ix_tests_project_id'), table_name='tests')
    op.drop_index(op.f('ix_tests_prerequisite_test_id'), table_name='tests')
    op.drop_table('tests')
    op.drop_index(op.f('ix_test_suites_module_id'), table_name='test_suites')
    op.drop_table('test_suites')
    op.drop_index(op.f('ix_screen_library_project_id'), table_name='screen_library')
    op.drop_index(op.f('ix_screen_library_folder_id'), table_name='screen_library')
    op.drop_index(op.f('ix_screen_library_build_id'), table_name='screen_library')
    op.drop_table('screen_library')
    op.drop_index(op.f('ix_screen_folders_project_id'), table_name='screen_folders')
    op.drop_table('screen_folders')
    op.drop_index(op.f('ix_modules_project_id'), table_name='modules')
    op.drop_table('modules')
    op.drop_index(op.f('ix_builds_project_id'), table_name='builds')
    op.drop_table('builds')
    op.drop_index(op.f('ix_batch_runs_project_id'), table_name='batch_runs')
    op.drop_table('batch_runs')
    op.drop_index(op.f('ix_projects_name'), table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
