"""
QA AI Automation — Stage 7: QA Sign-off Report
Aggregates metrics from Katalon TestOps, Jira, and Confluence,
generates the full report via Claude, and publishes everywhere.
"""

import json
import os
from typing import Optional
from pathlib import Path
from datetime import datetime

import requests

import sys
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import config
from tools.jira_client import JiraClient
from tools.confluence_client import ConfluenceClient
from tools.slack_notifier import SlackNotifier
from tools.ai_client import ai_chat


# ═════════════════════════════════════════════════
# Claude Report Generation Prompt
# ═════════════════════════════════════════════════

REPORT_PROMPT = """You are a senior QA lead writing the official release sign-off report.
Write a complete QA sign-off report with these EXACT sections:

1. EXECUTIVE SUMMARY
   One paragraph: overall release health, verdict, key metrics.

2. TEST COVERAGE
   - Tests run vs total available, pass rate
   - What was NOT tested and why
   - Risk mapping: >95% = Low risk, 90-95% = Medium risk, <90% = High risk

3. BUG BREAKDOWN
   Table format: severity | count | resolved | deferred | open
   Flag any Critical or Major open bugs explicitly with details.

4. RISK ASSESSMENT
   - Which features carry highest risk given current open bugs?
   - Safe to release? Any conditions or caveats?
   - Impact analysis of unresolved issues

5. FLAKY TEST ANALYSIS
   - List flaky tests with likely root cause per test
   - Recommended fix for each
   - Impact on test reliability metrics

6. GAPS & DEFERRALS
   - Untested requirements with justification
   - Deferred items with owner and target version
   - Explicit acknowledgement of known limitations

7. SIGN-OFF VERDICT
   Exactly one of:
   ✅ APPROVED FOR RELEASE — no conditions, all criteria met
   ⚠️ CONDITIONAL APPROVAL — list specific conditions that must be met before go-live
   ❌ NOT APPROVED — list blockers that must be resolved first

Formatting rules:
- Be direct and factual — stakeholders are PMs, devs, and the CTO
- Use bullet points, not walls of text
- Include specific numbers, not vague qualifiers
- End with: "Report generated by AI QA system — reviewed by [QA_LEAD_NAME]"

Return the report as plain text with markdown-style headings (# ## ###).
Do NOT wrap in JSON."""


# ═════════════════════════════════════════════════
# Metrics Collection
# ═════════════════════════════════════════════════

def collect_katalon_metrics(sprint_id: str) -> dict:
    """Fetch test execution metrics from Katalon TestOps API.

    Args:
        sprint_id: Sprint identifier for filtering results.

    Returns:
        dict with total, passed, failed, flaky, pass_rate, flaky_details.
    """
    print("📊 Collecting Katalon TestOps metrics...")

    if not config.KATALON_API_KEY:
        print("   ⚠️  Katalon API key not configured — using placeholder metrics")
        return {
            "total": 0, "passed": 0, "failed": 0, "flaky": 0,
            "pass_rate": 0, "flaky_details": [],
        }

    try:
        headers = {"Authorization": f"Bearer {config.KATALON_API_KEY}"}
        resp = requests.get(
            f"{config.KATALON_TESTOPS_URL}/api/v1/test-runs",
            headers=headers,
            params={
                "projectId": config.KATALON_PROJECT_ID,
                "sprintId": sprint_id,
            },
        )
        resp.raise_for_status()
        data = resp.json()

        total = data.get("totalTests", 0)
        passed = data.get("passedTests", 0)
        failed = data.get("failedTests", 0)
        flaky = data.get("flakyTests", 0)
        pass_rate = round((passed / total) * 100, 1) if total else 0

        return {
            "total": total,
            "passed": passed,
            "failed": failed,
            "flaky": flaky,
            "pass_rate": pass_rate,
            "flaky_details": data.get("flakyTestDetails", []),
        }

    except Exception as e:
        print(f"   ⚠️  Katalon API error: {e}")
        return {
            "total": 0, "passed": 0, "failed": 0, "flaky": 0,
            "pass_rate": 0, "flaky_details": [],
        }


def collect_jira_metrics(fix_version: str) -> dict:
    """Fetch bug metrics from Jira for the given fix version.

    Args:
        fix_version: Release version string (e.g. "v2.3.0").

    Returns:
        dict with bug counts by severity and status.
    """
    print("🐛 Collecting Jira bug metrics...")
    jira = JiraClient()

    try:
        jql = (
            f'project = {config.JIRA_PROJECT_KEY} '
            f'AND issuetype = {config.JIRA_BUG_ISSUE_TYPE} '
            f'AND fixVersion = "{fix_version}"'
        )
        bugs = jira.search_issues(jql, max_results=200)

        result = {
            "total": len(bugs),
            "critical": 0,
            "major": 0,
            "minor": 0,
            "trivial": 0,
            "resolved": 0,
            "open": 0,
            "deferred": 0,
            "bugs_detail": [],
        }

        for bug in bugs:
            fields = bug.get("fields", {})
            priority = fields.get("priority", {}).get("name", "Medium")
            status = fields.get("status", {}).get("name", "Open")
            labels = [l.lower() for l in fields.get("labels", [])]

            if priority in ("Highest", "Critical"):
                result["critical"] += 1
            elif priority == "High":
                result["major"] += 1
            elif priority in ("Medium", "Low"):
                result["minor"] += 1
            else:
                result["trivial"] += 1

            if status == "Done":
                result["resolved"] += 1
            elif "deferred" in labels:
                result["deferred"] += 1
            else:
                result["open"] += 1

            result["bugs_detail"].append({
                "key": bug["key"],
                "summary": fields.get("summary", ""),
                "priority": priority,
                "status": status,
                "component": (
                    fields.get("components", [{}])[0].get("name", "")
                    if fields.get("components") else ""
                ),
            })

        print(f"   → {result['total']} bugs found ({result['critical']} critical, {result['open']} open)")
        return result

    except Exception as e:
        print(f"   ⚠️  Jira API error: {e}")
        return {
            "total": 0, "critical": 0, "major": 0, "minor": 0,
            "trivial": 0, "resolved": 0, "open": 0, "deferred": 0,
            "bugs_detail": [],
        }


def collect_cycle_metrics(sprint_id: str, fix_version: str) -> dict:
    """Collect all metrics for a test cycle from all sources.

    Args:
        sprint_id: Sprint identifier.
        fix_version: Release version string.

    Returns:
        Combined metrics dict for report generation.
    """
    katalon_metrics = collect_katalon_metrics(sprint_id)
    jira_metrics = collect_jira_metrics(fix_version)

    # Try to get FRD content for coverage analysis
    frd_text = ""
    if config.FRD_PAGE_ID:
        try:
            confluence = ConfluenceClient()
            frd_text = confluence.get_page_body_text(config.FRD_PAGE_ID)
            print(f"📄 FRD content loaded ({len(frd_text)} chars)")
        except Exception as e:
            print(f"   ⚠️  Could not load FRD: {e}")

    return {
        "sprint_id": sprint_id,
        "fix_version": fix_version,
        "date": datetime.now().strftime("%Y-%m-%d"),
        "test_execution": katalon_metrics,
        "bugs": jira_metrics,
        "frd_text": frd_text,
    }


# ═════════════════════════════════════════════════
# Report Generation
# ═════════════════════════════════════════════════

def generate_report(metrics: dict) -> str:
    """Use Claude to write the full QA sign-off report narrative.

    Args:
        metrics: Combined metrics from collect_cycle_metrics().

    Returns:
        Complete report text with all 7 sections.
    """
    print("✍️  Generating report...")

    # Prepare metrics summary
    metrics_for_ai = {
        "sprint_id": metrics["sprint_id"],
        "fix_version": metrics["fix_version"],
        "date": metrics["date"],
        "test_execution": metrics["test_execution"],
        "bugs": {
            k: v for k, v in metrics["bugs"].items()
            if k != "bugs_detail"
        },
        "open_bugs_detail": [
            b for b in metrics["bugs"].get("bugs_detail", [])
            if b.get("status") != "Done"
        ][:20],
    }

    content = f"Generate the QA sign-off report for this cycle:\n\n{json.dumps(metrics_for_ai, indent=2)}"

    # Include FRD excerpt for coverage analysis
    frd = metrics.get("frd_text", "")
    if frd:
        content += f"\n\nFRD content for coverage analysis (excerpt):\n{frd[:4000]}"

    report = ai_chat(REPORT_PROMPT, content)
    print(f"   → Report generated ({len(report)} chars)")
    return report


def extract_verdict(report_text: str) -> str:
    """Extract the sign-off verdict from the report text.

    Returns:
        Verdict string (e.g. "✅ APPROVED FOR RELEASE").
    """
    for line in report_text.splitlines():
        stripped = line.strip()
        if any(v in stripped for v in ["✅", "⚠️", "❌"]):
            if any(k in stripped.upper() for k in ["APPROVED", "NOT APPROVED"]):
                return stripped
    return "Verdict not found in report"


# ═════════════════════════════════════════════════
# Publishing
# ═════════════════════════════════════════════════

def publish_report(report_text: str, metrics: dict) -> str:
    """Publish the sign-off report to Confluence.

    Args:
        report_text: Full report narrative.
        metrics: Cycle metrics for summary panel.

    Returns:
        URL of the published Confluence page.
    """
    print("📄 Publishing to Confluence...")
    confluence = ConfluenceClient()

    version = metrics["fix_version"]
    date = metrics["date"]
    title = f"QA Sign-off Report — {version} ({date})"

    test_exec = metrics.get("test_execution", {})
    bugs = metrics.get("bugs", {})
    summary = (
        f"Pass rate: <strong>{test_exec.get('pass_rate', 0)}%</strong> | "
        f"Open bugs: <strong>{bugs.get('open', 0)}</strong> | "
        f"Critical: <strong>{bugs.get('critical', 0)}</strong>"
    )

    url = confluence.publish_report(
        title=title,
        report_text=report_text,
        metrics_summary=summary,
    )

    print(f"   → Published: {url}")
    return url


def notify_slack(metrics: dict, report_url: str, verdict: str) -> None:
    """Post the sign-off digest card to Slack.

    Args:
        metrics: Cycle metrics.
        report_url: URL of the Confluence report.
        verdict: Sign-off verdict string.
    """
    print("💬 Posting Slack digest...")
    slack = SlackNotifier()

    test_exec = metrics.get("test_execution", {})
    bugs = metrics.get("bugs", {})

    slack.post_digest_card(
        fix_version=metrics["fix_version"],
        pass_rate=test_exec.get("pass_rate", 0),
        open_bugs=bugs.get("open", 0),
        critical_bugs=bugs.get("critical", 0),
        resolved_bugs=bugs.get("resolved", 0),
        flaky_tests=test_exec.get("flaky", 0),
        verdict=verdict,
        report_url=report_url,
    )


# ═════════════════════════════════════════════════
# Full Pipeline
# ═════════════════════════════════════════════════

def run_signoff_pipeline(
    sprint_id: str,
    fix_version: str,
    publish: bool = True,
) -> dict:
    """Run the complete QA sign-off pipeline.

    1. Collect metrics from Katalon, Jira, Confluence
    2. Generate report narrative via Claude
    3. Publish to Confluence
    4. Post Slack digest card
    5. Return verdict

    Args:
        sprint_id: Sprint identifier.
        fix_version: Release version string.
        publish: Whether to publish to Confluence and Slack.

    Returns:
        dict with keys: metrics, report, verdict, confluence_url
    """
    print("\n" + "=" * 60)
    print("🚀 Stage 7: QA Sign-off Report Pipeline")
    print("=" * 60)

    # Step 1: Collect metrics
    metrics = collect_cycle_metrics(sprint_id, fix_version)

    # Step 2: Generate report
    report = generate_report(metrics)

    # Step 3: Extract verdict
    verdict = extract_verdict(report)
    print(f"\n📋 Verdict: {verdict}")

    result = {
        "metrics": metrics,
        "report": report,
        "verdict": verdict,
        "confluence_url": None,
    }

    if publish:
        # Step 4: Publish to Confluence
        try:
            result["confluence_url"] = publish_report(report, metrics)
        except Exception as e:
            print(f"   ⚠️  Confluence publish failed: {e}")

        # Step 5: Post to Slack
        try:
            notify_slack(
                metrics,
                result["confluence_url"] or "Report URL unavailable",
                verdict,
            )
        except Exception as e:
            print(f"   ⚠️  Slack notification failed: {e}")

    # Save report locally as well
    reports_dir = Path(config.REPORTS_DIR)
    reports_dir.mkdir(parents=True, exist_ok=True)
    local_path = reports_dir / f"signoff_{fix_version}_{metrics['date']}.md"
    local_path.write_text(report, encoding="utf-8")
    print(f"💾 Report saved locally: {local_path}")

    print(f"\n✅ Sign-off pipeline complete!")
    return result


# ═════════════════════════════════════════════════
# CLI Entry Point
# ═════════════════════════════════════════════════

if __name__ == "__main__":
    import argparse

    parser = argparse.ArgumentParser(description="QA Sign-off Report Pipeline")
    parser.add_argument("--sprint-id", required=True, help="Sprint identifier")
    parser.add_argument("--fix-version", required=True, help="Release version")
    parser.add_argument("--no-publish", action="store_true", help="Skip publishing")
    args = parser.parse_args()

    result = run_signoff_pipeline(
        sprint_id=args.sprint_id,
        fix_version=args.fix_version,
        publish=not args.no_publish,
    )

    print(f"\n📊 Report preview (first 2000 chars):")
    print(result["report"][:2000])
